### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by dgozman** [mezzoeditor/zhtml#1]
- .split(regex) should be done in processTemplate;
- whitelist some boolean attributes to allow for non-boolean values;
- `<div z-pre>${0} {1}</div>` to preserve whitespace.

**Comment by aslushnikov** [comment]
> <div z-pre>${0} {1}</div> to preserve whitespace.

This is now addressed [creatively](https://github.com/mezzoeditor/zhtml/commit/8481a0dd92f6889fcaaa615325e5c90e42de0b52), but seems to be working nicely.
