### ISSUE TITLE
Unable to set plain attributes to element if the attribute given by an interpolation

### ISSUE THREAD

**Issue by Hyperseeker** [mezzoeditor/zhtml#4]
Example:

`<input type="checkbox" ${component.default ? "checked='true'" : ""}>`

vs.

`<input type="checkbox" ${component.default ? "checked" : ""}>`

I'm trying to render a checkbox that ought to be checked by default if a condition is fulfilled. `<input disabled>` works, but `<input ${"disabled"}>` doesn't, even though it's supposed to be the same token.

If I want to make the example above work, I have to declare the attribute fully: in my case, `${"checked='true'"}`. Not a dealbreaker, but I don't see why it shouldn't work.

**Comment by aslushnikov** [comment]
Indeed; I stumbled upon this a few times too. Fixed in 1.7.0 (latest)

Thank you for filing the issue!
